/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        pandeum: {
          bg: '#0B0F17',
          'bg-2': '#090C14',
          surface: '#101522',
          card: '#151B2A',
          'card-hover': '#1A2234',
          primary: '#6E42FF',
          'primary-hover': '#835DFF',
          'primary-glow': 'rgba(124,77,255,.35)',
          success: '#27C26A',
          warning: '#F3B53F',
          danger: '#FF5D73',
          text: '#FFFFFF',
          'text-secondary': '#AEB5C5',
          'text-muted': '#7E879E',
          border: 'rgba(255,255,255,.08)',
          divider: 'rgba(255,255,255,.05)',
        },
        background: '#07050d',
        surface: '#0c0a15',
        card: '#120f24',
        cardHover: '#18142a',
        primary: '#7c3aed',
        'theme-bg': 'var(--color-bg)',
        'theme-bg-2': 'var(--color-bg-2)',
        'theme-surface': 'var(--color-surface)',
        'theme-sidebar': 'var(--color-sidebar)',
        'theme-card': 'var(--color-card)',
        'theme-card-hover': 'var(--color-card-hover)',
        'theme-border': 'var(--color-border)',
        'theme-divider': 'var(--color-divider)',
        'theme-text': 'var(--color-text)',
        'theme-text-secondary': 'var(--color-text-secondary)',
        'theme-text-tertiary': 'var(--color-text-tertiary)',
        'theme-text-muted': 'var(--color-text-muted)',
      },
      backgroundImage: {
        'gradient-glow': 'linear-gradient(135deg, rgba(124,58,237,0.15) 0%, rgba(99,102,241,0.05) 100%)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '18px',
        'xl': '22px',
        '2xl': '24px',
      },
      boxShadow: {
        'pandeum-xs': '0 2px 8px rgba(0,0,0,.10)',
        'pandeum-sm': '0 8px 20px rgba(0,0,0,.14)',
        'pandeum-md': '0 12px 30px rgba(0,0,0,.18)',
        'pandeum-lg': '0 20px 45px rgba(0,0,0,.24)',
        'pandeum-xl': '0 30px 70px rgba(0,0,0,.35)',
        'pandeum-sidebar': '0 20px 50px rgba(0,0,0,.25)',
        'glow': '0 0 25px -5px rgba(124, 58, 237, 0.3)',
      },
      transitionDuration: {
        'hover': '180ms',
        'enter': '200ms',
        'drawer': '300ms',
        'modal': '350ms',
      },
      transitionTimingFunction: {
        'pandeum': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      animation: {
        'fade-in': 'fade-in 250ms cubic-bezier(0.22, 1, 0.36, 1)',
        'slide-up': 'slide-up 300ms cubic-bezier(0.22, 1, 0.36, 1)',
        'slide-down': 'slide-down 300ms cubic-bezier(0.22, 1, 0.36, 1)',
        'drawer-in': 'drawer-in 300ms cubic-bezier(0.22, 1, 0.36, 1)',
        'scale-in': 'scale-in 200ms cubic-bezier(0.22, 1, 0.36, 1)',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'float-slow': 'float 8s ease-in-out 1s infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'breath': 'breath 4s ease-in-out infinite',
        'slide-in-left': 'slide-in-left 350ms cubic-bezier(0.22, 1, 0.36, 1)',
        'slide-in-right': 'slide-in-right 350ms cubic-bezier(0.22, 1, 0.36, 1)',
        'appear': 'appear 400ms cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'drawer-in': {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 12px rgba(124,77,255,.15)' },
          '50%': { boxShadow: '0 0 24px rgba(124,77,255,.25)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'breath': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'appear': {
          '0%': { opacity: '0', transform: 'translateY(6px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
